CREATE TABLE data_migration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL,
    source_sha256 TEXT NOT NULL UNIQUE,
    source_path TEXT NOT NULL,
    backup_path TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('completed')),
    row_counts_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    verification_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE agent_thread (
    thread_id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    summary TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_agent_thread_owner
    ON agent_thread(owner_id, updated_at DESC);

CREATE TABLE agent_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id TEXT NOT NULL REFERENCES agent_thread(thread_id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_agent_message_thread
    ON agent_message(thread_id, id);

CREATE TABLE agent_tool_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id TEXT NOT NULL REFERENCES agent_thread(thread_id) ON DELETE CASCADE,
    tool_name TEXT NOT NULL,
    arguments_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL,
    duration_ms INTEGER NOT NULL,
    result_preview TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE agent_memory_setting (
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY(owner_id, scope_type, scope_id)
);

CREATE TABLE agent_memory (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    memory_type TEXT NOT NULL CHECK(memory_type IN ('PROFILE', 'TASK')),
    field_key TEXT,
    content TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('pending', 'active', 'deleted')),
    source TEXT NOT NULL CHECK(
        source IN ('explicit_chat', 'inferred_chat', 'profile_ui', 'teaching_plan')
    ),
    source_thread_id TEXT,
    confidence DOUBLE PRECISION CHECK(
        confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)
    ),
    expires_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    purge_after TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_agent_memory_scope_status
    ON agent_memory(owner_id, scope_type, scope_id, status, updated_at DESC);
CREATE INDEX idx_agent_memory_expiry
    ON agent_memory(status, expires_at, purge_after);
CREATE INDEX idx_agent_memory_field
    ON agent_memory(owner_id, scope_type, scope_id, field_key, status);

CREATE TABLE agent_memory_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id TEXT,
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_agent_memory_audit_scope
    ON agent_memory_audit(owner_id, scope_type, scope_id, created_at DESC);
CREATE INDEX idx_agent_memory_audit_memory
    ON agent_memory_audit(memory_id, created_at DESC);

CREATE TABLE prompt_version (
    prompt_key TEXT NOT NULL,
    version TEXT NOT NULL,
    content TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_by TEXT NOT NULL DEFAULT 'system',
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (prompt_key, version)
);
CREATE INDEX idx_prompt_version_active
    ON prompt_version(prompt_key, active);
CREATE UNIQUE INDEX uq_prompt_version_one_active
    ON prompt_version(prompt_key) WHERE active;

CREATE TABLE prompt_experiment (
    prompt_key TEXT PRIMARY KEY,
    experiment_key TEXT NOT NULL,
    variants_json JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE prompt_run (
    run_id TEXT PRIMARY KEY,
    prompt_key TEXT NOT NULL,
    version TEXT NOT NULL,
    experiment_key TEXT,
    variant TEXT,
    subject_key TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'started',
    latency_ms INTEGER,
    input_characters INTEGER NOT NULL DEFAULT 0,
    output_characters INTEGER NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION,
    feedback TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ
);
CREATE INDEX idx_prompt_run_metrics
    ON prompt_run(prompt_key, version, created_at DESC);

CREATE TABLE llm_trace (
    call_id TEXT PRIMARY KEY,
    trace_id TEXT NOT NULL,
    span_id TEXT NOT NULL,
    parent_span_id TEXT,
    user_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    feature TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'started',
    error_type TEXT,
    error_message TEXT NOT NULL DEFAULT '',
    valid_json BOOLEAN,
    input_tokens INTEGER,
    output_tokens INTEGER,
    total_tokens INTEGER,
    token_source TEXT NOT NULL DEFAULT 'unavailable',
    cost_usd DOUBLE PRECISION,
    latency_ms INTEGER,
    first_token_latency_ms INTEGER,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ
);
CREATE INDEX idx_llm_trace_time ON llm_trace(started_at DESC);
CREATE INDEX idx_llm_trace_feature ON llm_trace(feature, started_at DESC);
CREATE INDEX idx_llm_trace_user ON llm_trace(user_id, started_at DESC);
CREATE INDEX idx_llm_trace_session ON llm_trace(session_id, started_at DESC);
CREATE INDEX idx_llm_trace_trace ON llm_trace(trace_id, started_at);
