package com.redculture.platform.service.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpServer;
import com.redculture.platform.config.AppMapProperties;
import com.redculture.platform.entity.ContentChunk;
import com.redculture.platform.enums.ActivityType;
import com.redculture.platform.enums.EntityType;
import com.redculture.platform.service.KnowledgeRetriever;
import com.redculture.platform.service.SchoolMapService;
import com.redculture.platform.service.TeachingActivityPlanService;
import com.redculture.platform.vo.GeneratedTeachingPlanResponse;
import com.redculture.platform.vo.LocalEduResourceSummaryVO;
import com.redculture.platform.vo.SchoolMapDetailVO;
import com.redculture.platform.vo.SchoolResourceItemVO;
import com.redculture.platform.vo.SchoolSummaryVO;
import com.redculture.platform.vo.request.TeachingPlanGenerateRequest;
import com.redculture.platform.vo.ai.KnowledgeChunkVO;
import com.redculture.platform.vo.ai.KnowledgeCitationCandidateVO;
import com.redculture.platform.vo.ai.KnowledgeRetrieveResult;
import com.redculture.platform.vo.ai.KnowledgeRetrievalStatus;
import org.junit.jupiter.api.Test;

import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class AiTeachingPlanServiceImplTest {

    @Test
    void generatePlanSendsJsonBodyAndUsesLlmResponse() throws Exception {
        AtomicReference<String> capturedBody = new AtomicReference<>();
        HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.createContext("/llm/teaching-plan/generate", exchange -> {
            capturedBody.set(new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8));
            byte[] response = ("{\"generationStatus\":\"completed\",\"message\":\"generated by llm\","
                    + "\"theme\":\"LLM theme\",\"objectives\":[\"objective\"],\"citations\":[]}")
                    .getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "application/json; charset=utf-8");
            exchange.sendResponseHeaders(200, response.length);
            exchange.getResponseBody().write(response);
            exchange.close();
        });
        server.start();

        try {
            SchoolMapService schoolMapService = mock(SchoolMapService.class);
            when(schoolMapService.getSchoolDetail(1L)).thenReturn(schoolDetail());
            AiTeachingPlanServiceImpl service = newService(
                    schoolMapService,
                    mock(TeachingActivityPlanService.class),
                    Collections.emptyList(),
                    "http://127.0.0.1:" + server.getAddress().getPort()
            );

            GeneratedTeachingPlanResponse result = service.generatePlan(request());

            assertEquals("completed", result.getGenerationStatus());
            assertEquals("generated by llm", result.getMessage());
            assertFalse(capturedBody.get().isBlank());
            assertTrue(capturedBody.get().contains("\"request\""));
        } finally {
            server.stop(0);
        }
    }

    @Test
    void generatePlanRejectsUnavailableSchoolBeforeLlmCall() {
        SchoolMapService schoolMapService = mock(SchoolMapService.class);
        AiTeachingPlanServiceImpl service = newService(schoolMapService, mock(TeachingActivityPlanService.class),
                Collections.emptyList(), "");
        TeachingPlanGenerateRequest request = request();

        when(schoolMapService.getSchoolDetail(1L)).thenReturn(null);

        assertThrows(IllegalArgumentException.class, () -> service.generatePlan(request));
    }

    @Test
    void generatePlanReturnsLocalDegradedStructureWhenLlmUnavailable() {
        SchoolMapService schoolMapService = mock(SchoolMapService.class);
        TeachingActivityPlanService teachingActivityPlanService = mock(TeachingActivityPlanService.class);
        ContentChunk chunk = new ContentChunk();
        chunk.setChunkId(9L);
        chunk.setEntityType(EntityType.RESOURCE);
        chunk.setEntityId(2L);
        chunk.setChunkTitle("敬老服务资源说明");
        chunk.setChunkText("可组织学生开展尊老爱老、志愿服务和社会责任教育。");

        AiTeachingPlanServiceImpl service = newService(schoolMapService, teachingActivityPlanService,
                List.of(chunk), "");
        when(schoolMapService.getSchoolDetail(1L)).thenReturn(schoolDetail());

        GeneratedTeachingPlanResponse response = service.generatePlan(request());

        assertEquals("degraded", response.getGenerationStatus());
        assertEquals("敬老志愿服务", response.getTheme());
        assertFalse(response.getObjectives().isEmpty());
        assertFalse(response.getCitations().isEmpty());
        assertEquals("ok", response.getRetrievalStatus());
        assertEquals(List.of("vector+hybrid-rerank"), response.getRetrievalMethods());
        verify(teachingActivityPlanService, never()).createPlan(any());
    }

    private AiTeachingPlanServiceImpl newService(SchoolMapService schoolMapService,
                                                 TeachingActivityPlanService teachingActivityPlanService,
                                                 List<ContentChunk> chunks,
                                                 String llmBaseUrl) {
        KnowledgeRetriever knowledgeRetriever = mock(KnowledgeRetriever.class);
        AppMapProperties properties = new AppMapProperties();
        properties.setLlmServiceBaseUrl(llmBaseUrl);

        KnowledgeRetrieveResult retrieval = new KnowledgeRetrieveResult();
        retrieval.setRetrievalStatus(KnowledgeRetrievalStatus.OK);
        retrieval.setChunks(chunks.stream().map(chunk -> {
            KnowledgeChunkVO value = new KnowledgeChunkVO();
            value.setChunkId(chunk.getChunkId());
            value.setCitationId("chunk:" + chunk.getChunkId());
            value.setEntityType(chunk.getEntityType().getValue());
            value.setEntityId(chunk.getEntityId());
            value.setTitle(chunk.getChunkTitle());
            value.setText(chunk.getChunkText());
            value.setSourceId(chunk.getSourceId());
            value.setRetrievalMethod("vector+hybrid-rerank");
            return value;
        }).toList());
        retrieval.setCitationCandidates(chunks.stream().map(chunk -> {
            KnowledgeCitationCandidateVO value = new KnowledgeCitationCandidateVO();
            value.setCitationId("chunk:" + chunk.getChunkId());
            value.setTitle(chunk.getChunkTitle());
            value.setSourceType("content_chunk");
            value.setRelatedEntityType(chunk.getEntityType().getValue());
            value.setRelatedEntityId(chunk.getEntityId());
            value.setExcerpt(chunk.getChunkText());
            return value;
        }).toList());
        when(knowledgeRetriever.retrieve(any())).thenReturn(retrieval);

        return new AiTeachingPlanServiceImpl(
                schoolMapService,
                teachingActivityPlanService,
                knowledgeRetriever,
                properties,
                new ObjectMapper()
        );
    }

    private TeachingPlanGenerateRequest request() {
        TeachingPlanGenerateRequest request = new TeachingPlanGenerateRequest();
        request.setSchoolId(1L);
        request.setGrade("四年级");
        request.setTheme("敬老志愿服务");
        request.setActivityType(ActivityType.VOLUNTEER_SERVICE);
        request.setDurationMinutes(120);
        request.setPracticeRequired(true);
        return request;
    }

    private SchoolMapDetailVO schoolDetail() {
        SchoolSummaryVO school = new SchoolSummaryVO();
        school.setSchoolId(1L);
        school.setSchoolName("里庄小学");

        LocalEduResourceSummaryVO resource = new LocalEduResourceSummaryVO();
        resource.setResourceId(2L);
        resource.setResourceName("常安镇敬老院");
        resource.setEducationValue("适合开展尊老爱老、志愿服务、社会责任教育。");

        SchoolResourceItemVO item = new SchoolResourceItemVO();
        item.setSchoolId(1L);
        item.setResourceId(2L);
        item.setDistanceMeters(1800);
        item.setEducationThemeSummary("可开展敬老爱老与社会责任主题实践活动");
        item.setResource(resource);

        SchoolMapDetailVO detail = new SchoolMapDetailVO();
        detail.setSchool(school);
        detail.setResources(List.of(item));
        detail.setActivityPlans(Collections.emptyList());
        return detail;
    }
}
