<script setup>
import { onMounted, reactive, ref } from "vue";
import { Archive, ArchiveRestore, Clock3, History, MapPin, RefreshCw, Trash2 } from "@lucide/vue";
import AppShell from "@/components/AppShell.vue";
import InlineNotice from "@/components/InlineNotice.vue";
import LoadingBlock from "@/components/LoadingBlock.vue";
import { api } from "@/services/api";

const tab = ref("resources"); const loading = ref(true); const busy = ref(""); const notice = reactive({ tone: "", text: "" });
const resources = ref([]); const history = ref([]); const mode = ref("active"); const page = reactive({ pageNum: 1, pageSize: 20, total: 0 });
const date = (value) => value ? String(value).replace("T", " ").slice(0, 16) : "暂无时间";
onMounted(load);
async function load() { loading.value = true; await Promise.all([loadResources(), loadConversations()]); loading.value = false; }
async function loadResources(pageNum = page.pageNum) { try { const result = await api.get(`/api/student/resources/history?pageNum=${pageNum}&pageSize=${page.pageSize}`); resources.value = result.records || []; Object.assign(page, { pageNum: result.pageNum || pageNum, pageSize: result.pageSize || 20, total: result.total || 0 }); } catch (error) { showError(error); } }
async function loadConversations() { try { history.value = await api.get(`/api/ai/qa/history?status=${mode.value}`); } catch (error) { showError(error); } }
async function switchTab(value) { tab.value = value; if (value === "resources" && !resources.value.length) await loadResources(1); if (value === "qa" && !history.value.length) await loadConversations(); }
async function removeResource(resourceId) { if (!window.confirm("删除这条浏览记录？")) return; busy.value = `remove-${resourceId}`; try { await api.delete(`/api/student/resources/history/${resourceId}`); await loadResources(Math.min(page.pageNum, Math.max(1, Math.ceil((page.total - 1) / page.pageSize)))); notice.tone = "success"; notice.text = "浏览记录已删除"; } catch (error) { showError(error); } finally { busy.value = ""; } }
async function clearResources() { if (!resources.value.length || !window.confirm("确定清空全部浏览记录吗？")) return; busy.value = "clear"; try { await api.delete("/api/student/resources/history"); resources.value = []; page.total = 0; notice.tone = "success"; notice.text = "浏览记录已清空"; } catch (error) { showError(error); } finally { busy.value = ""; } }
async function switchMode(value) { mode.value = value; history.value = []; await loadConversations(); }
async function archive(threadId) { busy.value = threadId; try { await api.delete(`/api/ai/qa/history/${threadId}`); history.value = history.value.filter((item) => item.threadId !== threadId); } catch (error) { showError(error); } finally { busy.value = ""; } }
async function restore(threadId) { busy.value = threadId; try { await api.post(`/api/ai/qa/history/${threadId}/restore`); history.value = history.value.filter((item) => item.threadId !== threadId); } catch (error) { showError(error); } finally { busy.value = ""; } }
function showError(error) { notice.tone = "error"; notice.text = error?.message || "记录加载失败"; }
</script>
<template>
  <AppShell title="学习足迹" subtitle="回看浏览过的资源与曾经提出的问题">
    <InlineNotice v-if="notice.text" :tone="notice.tone">{{ notice.text }}</InlineNotice><LoadingBlock v-if="loading" />
    <template v-else><div class="footprint-tabs"><button type="button" :class="{active:tab==='resources'}" @click="switchTab('resources')"><MapPin :size="17" />资源浏览</button><button type="button" :class="{active:tab==='qa'}" @click="switchTab('qa')"><History :size="17" />问答记录</button></div>
      <section v-if="tab === 'resources'" class="page-panel"><div class="panel-header"><div><h2>资源浏览</h2><p>记录你最近探索过的红色文化资源</p></div><button class="ghost-button danger" type="button" :disabled="busy==='clear' || !resources.length" @click="clearResources"><Trash2 :size="15" />清空记录</button></div><div v-if="resources.length" class="resource-grid"><article v-for="item in resources" :key="item.resourceId" class="resource-card"><RouterLink :to="`/resource-discovery?resourceId=${item.resourceId}`" class="resource-link"><span class="resource-icon"><MapPin :size="18" /></span><strong>{{ item.resourceName }}</strong><small>{{ item.resourceCategory || '思政资源' }} · 浏览 {{ item.viewCount || 1 }} 次</small><p>{{ item.address || '地址待完善' }}</p><time><Clock3 :size="13" />{{ date(item.viewedAt) }}</time></RouterLink><button class="icon-button small danger" type="button" :disabled="busy === `remove-${item.resourceId}`" title="删除记录" @click="removeResource(item.resourceId)"><Trash2 :size="15" /></button></article></div><div v-else class="empty-state">暂无浏览记录，去资源发现中探索吧。</div><div v-if="page.total > page.pageSize" class="pager"><button type="button" :disabled="page.pageNum<=1" @click="loadResources(page.pageNum-1)">上一页</button><span>第 {{ page.pageNum }} 页 / 共 {{ Math.ceil(page.total / page.pageSize) }} 页</span><button type="button" :disabled="page.pageNum*page.pageSize>=page.total" @click="loadResources(page.pageNum+1)">下一页</button></div></section>
      <section v-else class="page-panel"><div class="panel-header"><div><h2>问答记录</h2><p>打开历史问题，继续你的学习探索</p></div><div class="history-mode"><button type="button" :class="{active:mode==='active'}" @click="switchMode('active')">当前记录</button><button type="button" :class="{active:mode==='archived'}" @click="switchMode('archived')">已归档</button></div></div><div v-if="history.length" class="qa-list"><article v-for="item in history" :key="item.threadId" class="qa-card"><RouterLink :to="`/assistant?threadId=${encodeURIComponent(item.threadId)}`" class="qa-main"><strong>{{ item.title || '未命名问题' }}</strong><p>{{ item.preview || '暂无回答摘要' }}</p><small>{{ item.messageCount || 0 }} 条消息 · 更新于 {{ date(item.updatedAt) }}</small></RouterLink><button v-if="mode==='active'" class="icon-button small" type="button" title="归档对话" @click="archive(item.threadId)"><Archive :size="15" /></button><button v-else class="icon-button small" type="button" title="恢复对话" @click="restore(item.threadId)"><ArchiveRestore :size="15" /></button></article></div><div v-else class="empty-state">{{ mode === 'archived' ? '暂无归档问答记录' : '暂无问答记录，去智能问答开始提问吧。' }}</div></section>
    </template>
  </AppShell>
</template>
<style scoped>
.footprint-tabs{display:flex;gap:8px;margin:14px 0}.footprint-tabs button,.history-mode button{display:inline-flex;align-items:center;gap:7px;padding:9px 13px;border:1px solid var(--line);border-radius:6px;background:#fff;color:var(--muted)}.footprint-tabs button.active,.history-mode button.active{border-color:var(--green);background:var(--green-soft);color:var(--green)}.resource-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:14px}.resource-card{display:flex;gap:8px;min-width:0;padding:13px;border:1px solid var(--line);border-radius:7px}.resource-link{display:grid;gap:7px;min-width:0;flex:1;color:inherit;text-decoration:none}.resource-link small,.resource-link p,.resource-link time{color:var(--muted);font-size:12px}.resource-link p{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.resource-link time{display:flex;align-items:center;gap:5px}.resource-icon{display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:#edf4ef;color:var(--green)}.icon-button.small{width:30px;height:30px;flex:none}.danger{color:#a14316!important}.pager{display:flex;justify-content:center;align-items:center;gap:10px;padding:0 14px 14px;color:var(--muted);font-size:13px}.pager button{padding:6px 10px;border:1px solid var(--line);border-radius:5px;background:#fff}.pager button:disabled{opacity:.5}.history-mode{display:flex;gap:5px}.qa-list{display:grid;gap:8px;padding:14px}.qa-card{display:flex;align-items:center;gap:10px;padding:13px;border:1px solid var(--line);border-radius:7px}.qa-main{display:grid;gap:6px;min-width:0;flex:1;color:inherit;text-decoration:none}.qa-main p{margin:0;overflow:hidden;color:var(--muted);text-overflow:ellipsis;white-space:nowrap}.qa-main small{color:var(--muted);font-size:12px}@media(max-width:900px){.resource-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.resource-grid{grid-template-columns:1fr}.panel-header{align-items:flex-start;gap:10px}.history-mode{flex-wrap:wrap}.footprint-tabs button{flex:1;justify-content:center}}
</style>
