<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from "vue";
import { Bookmark, MapPin, Search, Star } from "@lucide/vue";
import AppShell from "@/components/AppShell.vue";
import InlineNotice from "@/components/InlineNotice.vue";
import LoadingBlock from "@/components/LoadingBlock.vue";
import { api } from "@/services/api";
import { loadAmap } from "@/services/amap";
import { useSchoolStore } from "@/stores/school";
const school=useSchoolStore(), mapCanvas=ref(null), items=ref([]), selected=ref(null), loading=ref(true), notice=reactive({tone:"",text:""}), filters=reactive({keyword:"",category:"",favoritesOnly:false}), map=ref(null), AMap=ref(null), markers=[];
const visible=computed(()=>items.value);
onMounted(async()=>{try{await school.loadConfig();await refresh();await nextTick();AMap.value=await loadAmap(school.config);map.value=new AMap.value.Map(mapCanvas.value,{zoom:12,viewMode:"2D"});render();}catch(e){notice.tone="error";notice.text=e.message||"资源加载失败"}finally{loading.value=false}});onBeforeUnmount(()=>map.value?.destroy());watch(visible,render);
async function refresh(){try{const query=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value!==""&&value!==false&&value!=null)query.set(key,String(value))});items.value=await api.get(`/api/teacher/resources/nearby?${query}`);}catch(e){notice.tone="error";notice.text=e.message||"资源加载失败"}}
function render(){if(!map.value||!AMap.value)return;if(markers.length)map.value.remove(markers);markers.length=0;visible.value.forEach(item=>{if(item.longitude==null||item.latitude==null)return;const marker=new AMap.value.Marker({position:[Number(item.longitude),Number(item.latitude)],content:'<span class="resource-pin">资</span>',offset:new AMap.value.Pixel(-15,-15)});marker.on("click",()=>select(item));markers.push(marker)});if(markers.length){map.value.add(markers);map.value.setFitView(markers,false,[40,40,40,40],15)}}
function select(item){selected.value=item;if(map.value&&item.longitude!=null)map.value.setZoomAndCenter(15,[Number(item.longitude),Number(item.latitude)])}
async function toggle(item){try{if(item.favorited)await api.delete(`/api/teacher/resources/${item.resourceId}/favorite`);else await api.post(`/api/teacher/resources/${item.resourceId}/favorite`,{});item.favorited=!item.favorited}catch(e){notice.tone="error";notice.text=e.message||"操作失败"}}
function search(){refresh()} function distance(v){return v==null?"距离待核验":v>=1000?`${(v/1000).toFixed(1)} 公里`:`${v} 米`}
</script>
<template><AppShell title="资源发现" subtitle="查看本校已审核的周边思政教育资源并收藏常用地点"><InlineNotice v-if="notice.text" :tone="notice.tone">{{notice.text}}</InlineNotice><LoadingBlock v-if="loading"/><div v-else class="workspace"><section class="page-panel catalog"><form class="filters" @submit.prevent="search"><input v-model="filters.keyword" placeholder="搜索资源或教育主题"/><select v-model="filters.category"><option value="">全部类别</option><option value="red_culture">红色文化</option><option value="local_history">地方历史</option><option value="labor_education">劳动教育</option></select><label><input v-model="filters.favoritesOnly" type="checkbox" @change="search"/>仅收藏</label><button class="primary-button" type="submit"><Search :size="16"/>筛选</button></form><div class="resource-list"><button v-for="item in visible" :key="item.resourceId" class="resource-item" :class="{active:selected?.resourceId===item.resourceId}" type="button" @click="select(item)"><span><strong>{{item.resourceName}}</strong><small>{{item.resourceCategory||'思政资源'}} · {{distance(item.distanceMeters)}}</small></span><Star :size="17" :fill="item.favorited?'currentColor':'none'"/></button><div v-if="!visible.length" class="empty-state">暂无符合条件的资源</div></div></section><section class="page-panel map-panel"><div ref="mapCanvas" class="canvas"></div><aside v-if="selected" class="detail"><div><span class="badge">{{selected.resourceCategory}}</span><h2>{{selected.resourceName}}</h2></div><button class="icon-button" type="button" title="收藏" @click="toggle(selected)"><Bookmark :fill="selected.favorited?'currentColor':'none'" :size="18"/></button><p>{{selected.intro||selected.educationValue||'暂无资源简介'}}</p><dl><div><dt>地址</dt><dd>{{selected.address||'暂无'}}</dd></div><div><dt>出行</dt><dd>{{selected.travelMode||'待核验'}} · {{selected.durationMinutes||'-'}} 分钟</dd></div><div><dt>安全提示</dt><dd>{{selected.safetyNote||'暂无'}}</dd></div></dl></aside></section></div></AppShell></template>
<style scoped>.workspace{display:grid;grid-template-columns:minmax(310px,.8fr) minmax(0,1.2fr);gap:16px}.catalog{min-height:calc(100vh - 145px)}.filters{display:grid;gap:10px;padding:16px;border-bottom:1px solid var(--line)}.filters label{display:flex;align-items:center;gap:8px}.filters label input{width:auto;min-height:auto}.resource-list{display:grid;gap:7px;padding:12px}.resource-item{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:12px;border:1px solid var(--line);border-radius:6px;background:#fff;text-align:left}.resource-item.active,.resource-item:hover{border-color:var(--green);background:var(--green-soft)}.resource-item span{display:grid;gap:4px}.resource-item small{color:var(--muted)}.map-panel{position:relative;overflow:hidden;min-height:calc(100vh - 145px)}.canvas{height:100%;min-height:580px}.detail{position:absolute;right:14px;bottom:14px;left:14px;display:grid;grid-template-columns:1fr auto;gap:12px;padding:16px;border:1px solid var(--line);border-radius:6px;background:#fff;box-shadow:var(--shadow)}.detail h2{margin:8px 0 0;font-size:18px}.detail p,.detail dl{grid-column:1/-1;margin:0;color:var(--muted);line-height:1.6}.detail dl{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.detail dt{font-size:12px}.detail dd{margin:4px 0 0;color:var(--text);font-size:13px}:global(.resource-pin){display:grid;place-items:center;width:30px;height:30px;border:2px solid #fff;border-radius:50%;background:#a6382f;color:#fff;font-size:12px;font-weight:700;box-shadow:0 3px 10px rgba(0,0,0,.2)}@media(max-width:900px){.workspace{grid-template-columns:1fr}.catalog,.map-panel{min-height:auto}.canvas{min-height:460px}.detail dl{grid-template-columns:1fr}}</style>
