<script setup>
import { computed, onMounted, reactive, ref } from "vue";
import { Check, FileUp, MapPin, Send, Undo2 } from "@lucide/vue";
import AppShell from "@/components/AppShell.vue";
import InlineNotice from "@/components/InlineNotice.vue";
import LoadingBlock from "@/components/LoadingBlock.vue";
import { api, apiRequest } from "@/services/api";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();
const studentMode = computed(() => auth.user?.roleCode === "student");
const loading = ref(true); const notice = reactive({ tone: "", text: "" });
const tasks = ref([]); const detail = ref(null); const classes = ref([]); const selectedClass = ref(""); const submissions = ref([]); const stats = ref(null);
const submission = reactive({ content: "", selectedResourceIds: [], files: [] });
const review = reactive({ reviewAction: "approved", comment: "", grade: "good" });

onMounted(load);
async function load() { loading.value = true; try { if (studentMode.value) tasks.value = await api.get("/api/student/class-tasks"); else classes.value = await api.get("/api/teacher/classes/mine"); } catch (e) { error(e); } finally { loading.value = false; } }
async function chooseStudentTask(taskId) { try { detail.value = await api.get(`/api/student/tasks/${taskId}`); const current = detail.value.currentSubmission; submission.content = current?.content || ""; submission.selectedResourceIds = current?.selectedResourceIds || []; } catch (e) { error(e); } }
async function chooseClass() { detail.value = null; submissions.value = []; stats.value = null; if (!selectedClass.value) return; try { const item = await api.get(`/api/teacher/classes/${selectedClass.value}`); tasks.value = item.tasks || []; } catch (e) { error(e); } }
async function chooseTeacherTask(taskId) { try { const [items, summary] = await Promise.all([api.get(`/api/teacher/tasks/${taskId}/submissions`), api.get(`/api/teacher/tasks/${taskId}/statistics`)]); submissions.value = items; stats.value = summary; detail.value = tasks.value.find(item => item.taskId === taskId); } catch (e) { error(e); } }
async function submitWork() { if (!detail.value) return; try { const draft = await api.post(`/api/student/tasks/${detail.value.taskId}/submissions`, { content: submission.content, selectedResourceIds: submission.selectedResourceIds.map(Number) }); for (const file of submission.files) { const form = new FormData(); form.append("file", file); await apiRequest(`/api/student/submissions/${draft.submissionId}/attachments`, { method: "POST", body: form }); } await api.post(`/api/student/submissions/${draft.submissionId}/submit`, {}); notice.tone = "success"; notice.text = "任务已提交，等待教师评价"; submission.files = []; await chooseStudentTask(detail.value.taskId); await load(); } catch (e) { error(e); } }
function filesChanged(event) { submission.files = Array.from(event.target.files || []); }
async function reviewSubmission(item) { try { await api.post(`/api/teacher/submissions/${item.submissionId}/review`, review); notice.tone = "success"; notice.text = review.reviewAction === "returned" ? "已退回修改" : "评价已完成"; await chooseTeacherTask(detail.value.taskId); } catch (e) { error(e); } }
function error(e) { notice.tone = "error"; notice.text = e?.message || "操作失败"; }
function label(status) { return ({ pending: "待提交", submitted: "待评价", returned: "退回修改", completed: "已完成", overdue: "已逾期" })[status] || status; }
</script>

<template>
  <AppShell :title="studentMode ? '我的学习任务' : '学习任务管理'" :subtitle="studentMode ? '提交红色文化学习成果并查看教师评价' : '查看学生提交并完成评价'">
    <InlineNotice v-if="notice.text" :tone="notice.tone">{{ notice.text }}</InlineNotice><LoadingBlock v-if="loading" />
    <template v-else-if="studentMode"><div class="layout"><section class="page-panel"><div class="panel-header"><div><h2>我的任务</h2><p>点击任务开始提交</p></div></div><div class="list"><button v-for="task in tasks" :key="task.taskId" class="row" type="button" @click="chooseStudentTask(task.taskId)"><strong>{{ task.title }}</strong><span class="badge">{{ label(task.studentStatus) }}</span><small>截止：{{ task.dueAt || '未设置' }}</small></button></div></section><section class="page-panel"><div class="panel-header"><div><h2>{{ detail?.title || '任务详情' }}</h2><p>{{ detail?.description }}</p></div></div><div v-if="detail" class="body"><div v-if="detail.resources?.length" class="resources"><label v-for="item in detail.resources" :key="item.resourceId"><input v-model="submission.selectedResourceIds" type="checkbox" :value="item.resourceId" /><span><MapPin :size="15" />{{ item.resourceName }}<small>{{ item.address }}</small></span></label></div><label>学习感想<textarea v-model="submission.content" placeholder="记录你的学习收获与感想"></textarea></label><label>附件（图片、PDF 或 DOCX，最多3个）<input type="file" multiple accept="image/*,.pdf,.docx" @change="filesChanged" /></label><div v-if="detail.currentSubmission?.reviews?.length" class="reviews"><h3>教师评价</h3><p v-for="item in detail.currentSubmission.reviews" :key="item.reviewId">{{ item.grade }}：{{ item.comment }}</p></div><button class="primary-button" type="button" @click="submitWork"><Send :size="16" />提交任务</button></div><div v-else class="empty-state">选择左侧任务查看详情</div></section></div></template>
    <template v-else><section class="page-panel selector"><div class="panel-body"><label>选择班级<select v-model="selectedClass" @change="chooseClass"><option value="">请选择</option><option v-for="item in classes" :key="item.classId" :value="item.classId">{{ item.className }}</option></select></label></div></section><div class="layout"><section class="page-panel"><div class="panel-header"><div><h2>班级任务</h2></div></div><div class="list"><button v-for="task in tasks" :key="task.taskId" class="row" type="button" @click="chooseTeacherTask(task.taskId)"><strong>{{ task.title }}</strong><small>{{ task.taskType === 'map_exploration' ? '地图探索' : '学习任务' }} · {{ task.submissionRule }}</small></button></div></section><section class="page-panel"><div class="panel-header"><div><h2>{{ detail?.title || '提交批改' }}</h2><p v-if="stats">待提交 {{ stats.pendingCount }} · 待评价 {{ stats.submittedCount }} · 已完成 {{ stats.completedCount }}</p></div></div><div v-if="detail" class="body"><article v-for="item in submissions" :key="item.submissionId" class="submission"><h3>{{ item.studentName }} · 第{{ item.versionNo }}版 <span class="badge">{{ label(item.status) }}</span></h3><p>{{ item.content || '未填写文字内容' }}</p><small>提交：{{ item.submittedAt || '草稿' }}{{ item.late ? '（逾期）' : '' }}</small><ul><li v-for="file in item.attachments" :key="file.attachmentId"><a :href="`/api/student/attachments/${file.attachmentId}/download`" target="_blank">{{ file.originalFilename }}</a></li></ul><div v-if="item.status === 'submitted'" class="review"><select v-model="review.reviewAction"><option value="approved">通过</option><option value="returned">退回修改</option></select><select v-model="review.grade"><option value="excellent">优秀</option><option value="good">良好</option><option value="pass">合格</option><option value="needs_revision">待改进</option></select><textarea v-model="review.comment" placeholder="教师评语；退回时必填"></textarea><button class="primary-button" type="button" @click="reviewSubmission(item)"><Check v-if="review.reviewAction === 'approved'" :size="16" /><Undo2 v-else :size="16" />提交评价</button></div></article></div><div v-else class="empty-state">选择任务查看学生提交</div></section></div></template>
  </AppShell>
</template>

<style scoped>
.layout{display:grid;grid-template-columns:minmax(260px,.7fr) minmax(0,1.3fr);gap:16px;margin-top:16px}.list{display:grid;gap:8px;padding:14px}.row{display:grid;gap:6px;padding:13px;border:1px solid var(--line);border-radius:6px;background:#fff;text-align:left}.row:hover{border-color:var(--green);background:var(--green-soft)}.row small,.submission small{color:var(--muted)}.body{display:grid;gap:14px;padding:20px}.resources{display:grid;gap:8px}.resources label{display:flex;align-items:flex-start;gap:8px;padding:10px;border:1px solid var(--line);border-radius:6px}.resources input{width:auto;min-height:auto}.resources span{display:grid;gap:3px}.resources small{color:var(--muted)}.reviews,.submission{padding:14px;border:1px solid var(--line);border-radius:6px}.review{display:grid;grid-template-columns:150px 150px 1fr auto;gap:8px;margin-top:12px}.review textarea{min-height:42px}.selector{max-width:520px}@media(max-width:900px){.layout{grid-template-columns:1fr}.review{grid-template-columns:1fr}.review textarea{min-height:80px}}
</style>
