brokerClusterName=KnowledgeCluster
brokerName=knowledge-broker
brokerId=0
brokerRole=ASYNC_MASTER
flushDiskType=SYNC_FLUSH
autoCreateTopicEnable=false
autoCreateSubscriptionGroup=false
enablePropertyFilter=true
storePathRootDir=/home/rocketmq/store
