package com.redculture.platform.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.redculture.platform.entity.*;
import com.redculture.platform.enums.ReviewStatus;
import com.redculture.platform.mapper.*;
import com.redculture.platform.service.TaskSubmissionService;
import com.redculture.platform.service.TaskSubmissionStorageService;
import com.redculture.platform.vo.*;
import com.redculture.platform.vo.request.StudentTaskReviewRequest;
import com.redculture.platform.vo.request.StudentTaskSubmissionRequest;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import org.springframework.web.multipart.MultipartFile;

import java.time.LocalDateTime;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service
public class TaskSubmissionServiceImpl implements TaskSubmissionService {
    private static final Set<String> RULES = Set.of("text_only", "text_required", "attachment_required", "text_and_attachment");
    private static final Set<String> GRADES = Set.of("excellent", "good", "pass", "needs_revision");
    private final ClassLearningTaskMapper taskMapper; private final StudentTaskProgressMapper progressMapper;
    private final StudentTaskSubmissionMapper submissionMapper; private final StudentTaskAttachmentMapper attachmentMapper; private final StudentTaskReviewMapper reviewMapper;
    private final TaskResourceRelMapper taskResourceMapper; private final LocalEduResourceMapper resourceMapper;
    private final StudentProfileMapper studentMapper; private final TeacherProfileMapper teacherMapper; private final ClassMemberMapper memberMapper; private final ClassTeacherMapper classTeacherMapper;
    private final TaskSubmissionStorageService storage;

    public TaskSubmissionServiceImpl(ClassLearningTaskMapper taskMapper, StudentTaskProgressMapper progressMapper, StudentTaskSubmissionMapper submissionMapper, StudentTaskAttachmentMapper attachmentMapper, StudentTaskReviewMapper reviewMapper, TaskResourceRelMapper taskResourceMapper, LocalEduResourceMapper resourceMapper, StudentProfileMapper studentMapper, TeacherProfileMapper teacherMapper, ClassMemberMapper memberMapper, ClassTeacherMapper classTeacherMapper, TaskSubmissionStorageService storage) {
        this.taskMapper = taskMapper; this.progressMapper = progressMapper; this.submissionMapper = submissionMapper; this.attachmentMapper = attachmentMapper; this.reviewMapper = reviewMapper; this.taskResourceMapper = taskResourceMapper; this.resourceMapper = resourceMapper; this.studentMapper = studentMapper; this.teacherMapper = teacherMapper; this.memberMapper = memberMapper; this.classTeacherMapper = classTeacherMapper; this.storage = storage;
    }

    @Override public StudentTaskDetailVO studentTaskDetail(Long taskId, AuthCurrentUserVO user) { StudentProfile student = requireStudent(user); ClassLearningTask task = requirePublishedTask(taskId); requireActiveMember(task, student.getStudentId()); return taskDetail(task, currentSubmission(taskId, student.getStudentId())); }

    @Override @Transactional public StudentTaskSubmissionVO createSubmission(Long taskId, StudentTaskSubmissionRequest request, AuthCurrentUserVO user) {
        StudentProfile student = requireStudent(user); ClassLearningTask task = requirePublishedTask(taskId); requireActiveMember(task, student.getStudentId());
        StudentTaskSubmission current = currentSubmission(taskId, student.getStudentId());
        if (current != null && "draft".equals(current.getStatus())) { applySubmission(current, request); submissionMapper.updateById(current); return submissionVO(current); }
        if (current != null && "submitted".equals(current.getStatus())) throw new IllegalArgumentException("submission is awaiting review");
        if (current != null) { current.setCurrent(false); submissionMapper.updateById(current); }
        StudentTaskSubmission submission = new StudentTaskSubmission(); submission.setTaskId(taskId); submission.setStudentId(student.getStudentId()); submission.setVersionNo(current == null ? 1 : current.getVersionNo() + 1); submission.setStatus("draft"); submission.setCurrent(true); submission.setLate(false); applySubmission(submission, request); submissionMapper.insert(submission); return submissionVO(submission);
    }

    @Override @Transactional public StudentTaskAttachmentVO uploadAttachment(Long submissionId, MultipartFile file, AuthCurrentUserVO user) {
        StudentTaskSubmission submission = requireOwnedDraft(submissionId, requireStudent(user));
        long count = attachmentMapper.selectCount(new LambdaQueryWrapper<StudentTaskAttachment>().eq(StudentTaskAttachment::getSubmissionId, submissionId)); if (count >= 3) throw new IllegalArgumentException("at most 3 attachments are allowed");
        TaskSubmissionStorageService.StoredFile stored = storage.store(file);
        try { StudentTaskAttachment entity = new StudentTaskAttachment(); entity.setSubmissionId(submissionId); entity.setOriginalFilename(stored.filename()); entity.setStorageKey(stored.key()); entity.setContentType(stored.contentType()); entity.setFileSize(stored.size()); attachmentMapper.insert(entity); return attachmentVO(entity); }
        catch (RuntimeException exception) { storage.delete(stored.key()); throw exception; }
    }

    @Override @Transactional public StudentTaskSubmissionVO submit(Long submissionId, AuthCurrentUserVO user) {
        StudentProfile student = requireStudent(user); StudentTaskSubmission submission = requireOwnedDraft(submissionId, student); ClassLearningTask task = requirePublishedTask(submission.getTaskId()); requireActiveMember(task, student.getStudentId());
        validateSubmission(task, submission); submission.setStatus("submitted"); submission.setSubmittedAt(LocalDateTime.now()); submission.setLate(task.getDueAt() != null && task.getDueAt().isBefore(submission.getSubmittedAt())); submissionMapper.updateById(submission);
        StudentTaskProgress progress = requireProgress(task.getTaskId(), student.getStudentId()); progress.setStatus("submitted"); progressMapper.updateById(progress); return submissionVO(submission);
    }

    @Override public List<StudentTaskSubmissionVO> history(Long submissionId, AuthCurrentUserVO user) { StudentProfile student = requireStudent(user); StudentTaskSubmission submission = submissionMapper.selectById(submissionId); if (submission == null || !student.getStudentId().equals(submission.getStudentId())) throw new IllegalArgumentException("submission not found"); return submissionMapper.selectList(new LambdaQueryWrapper<StudentTaskSubmission>().eq(StudentTaskSubmission::getTaskId, submission.getTaskId()).eq(StudentTaskSubmission::getStudentId, student.getStudentId()).orderByDesc(StudentTaskSubmission::getVersionNo)).stream().map(this::submissionVO).toList(); }
    @Override public List<StudentTaskSubmissionVO> teacherSubmissions(Long taskId, AuthCurrentUserVO user) { requirePublisher(taskId, user); return submissionMapper.selectList(new LambdaQueryWrapper<StudentTaskSubmission>().eq(StudentTaskSubmission::getTaskId, taskId).eq(StudentTaskSubmission::getCurrent, true).orderByDesc(StudentTaskSubmission::getSubmittedAt)).stream().map(this::submissionVO).toList(); }
    @Override public StudentTaskSubmissionVO teacherSubmissionDetail(Long submissionId, AuthCurrentUserVO user) { StudentTaskSubmission submission = requireSubmission(submissionId); requirePublisher(submission.getTaskId(), user); return submissionVO(submission); }

    @Override @Transactional public StudentTaskSubmissionVO review(Long submissionId, StudentTaskReviewRequest request, AuthCurrentUserVO user) {
        StudentTaskSubmission submission = requireSubmission(submissionId); TeacherProfile teacher = requirePublisher(submission.getTaskId(), user); if (!"submitted".equals(submission.getStatus())) throw new IllegalArgumentException("only submitted work can be reviewed");
        if (request == null || !Set.of("approved", "returned").contains(request.getReviewAction())) throw new IllegalArgumentException("reviewAction must be approved or returned");
        if ("returned".equals(request.getReviewAction()) && !StringUtils.hasText(request.getComment())) throw new IllegalArgumentException("a return comment is required");
        if (StringUtils.hasText(request.getGrade()) && !GRADES.contains(request.getGrade())) throw new IllegalArgumentException("unsupported grade");
        StudentTaskReview review = new StudentTaskReview(); review.setSubmissionId(submissionId); review.setTeacherId(teacher.getTeacherId()); review.setReviewAction(request.getReviewAction()); review.setComment(request.getComment()); review.setGrade(request.getGrade()); review.setReviewedAt(LocalDateTime.now()); reviewMapper.insert(review);
        submission.setStatus("approved".equals(request.getReviewAction()) ? "completed" : "returned"); submissionMapper.updateById(submission); StudentTaskProgress progress = requireProgress(submission.getTaskId(), submission.getStudentId()); progress.setStatus(submission.getStatus()); progressMapper.updateById(progress); return submissionVO(submission);
    }

    @Override public TaskStatisticsVO statistics(Long taskId, AuthCurrentUserVO user) { requirePublisher(taskId, user); List<StudentTaskProgress> progress = progressMapper.selectList(new LambdaQueryWrapper<StudentTaskProgress>().eq(StudentTaskProgress::getTaskId, taskId)); ClassLearningTask task = requireTask(taskId); TaskStatisticsVO vo = new TaskStatisticsVO(); vo.setTaskId(taskId); vo.setPendingCount(progress.stream().filter(item -> "pending".equals(item.getStatus())).count()); vo.setSubmittedCount(progress.stream().filter(item -> "submitted".equals(item.getStatus())).count()); vo.setReturnedCount(progress.stream().filter(item -> "returned".equals(item.getStatus())).count()); vo.setCompletedCount(progress.stream().filter(item -> "completed".equals(item.getStatus())).count()); vo.setOverdueCount(task.getDueAt() != null && task.getDueAt().isBefore(LocalDateTime.now()) ? vo.getPendingCount() : 0); vo.setLateSubmissionCount(submissionMapper.selectCount(new LambdaQueryWrapper<StudentTaskSubmission>().eq(StudentTaskSubmission::getTaskId, taskId).eq(StudentTaskSubmission::getCurrent, true).eq(StudentTaskSubmission::getLate, true))); return vo; }
    @Override public List<TaskResourceVO> availableResources(AuthCurrentUserVO user) { if (user == null || !"teacher".equals(user.getRoleCode())) throw new IllegalArgumentException("teacher access required"); return resourceMapper.selectList(new LambdaQueryWrapper<LocalEduResource>().eq(LocalEduResource::getActive, true).eq(LocalEduResource::getReviewStatus, ReviewStatus.APPROVED).orderByAsc(LocalEduResource::getResourceName)).stream().map(this::resourceVO).toList(); }
    @Override public DownloadAttachment download(Long attachmentId, AuthCurrentUserVO user) { StudentTaskAttachment attachment = attachmentMapper.selectById(attachmentId); if (attachment == null) throw new IllegalArgumentException("attachment not found"); StudentTaskSubmission submission = requireSubmission(attachment.getSubmissionId()); if (!canReadSubmission(submission, user)) throw new IllegalArgumentException("attachment access denied"); Resource resource = storage.load(attachment.getStorageKey()); return new DownloadAttachment(resource, attachment.getOriginalFilename(), attachment.getContentType()); }

    private void applySubmission(StudentTaskSubmission entity, StudentTaskSubmissionRequest request) { if (request == null) return; entity.setContent(request.getContent()); List<Long> ids = request.getSelectedResourceIds() == null ? Collections.emptyList() : request.getSelectedResourceIds().stream().filter(Objects::nonNull).distinct().toList(); entity.setSelectedResourceIds(ids.stream().map(String::valueOf).collect(Collectors.joining(","))); }
    private void validateSubmission(ClassLearningTask task, StudentTaskSubmission submission) { String rule = task.getSubmissionRule() == null ? "text_required" : task.getSubmissionRule(); if (!RULES.contains(rule)) throw new IllegalStateException("task submission rule is invalid"); boolean text = StringUtils.hasText(submission.getContent()); long attachments = attachmentMapper.selectCount(new LambdaQueryWrapper<StudentTaskAttachment>().eq(StudentTaskAttachment::getSubmissionId, submission.getSubmissionId())); if (("text_required".equals(rule) || "text_and_attachment".equals(rule)) && !text) throw new IllegalArgumentException("task requires written content"); if (("attachment_required".equals(rule) || "text_and_attachment".equals(rule)) && attachments == 0) throw new IllegalArgumentException("task requires an attachment"); if ("map_exploration".equals(task.getTaskType())) { Set<Long> allowed = taskResourceMapper.selectList(new LambdaQueryWrapper<TaskResourceRel>().eq(TaskResourceRel::getTaskId, task.getTaskId())).stream().map(TaskResourceRel::getResourceId).collect(Collectors.toSet()); Set<Long> selected = selectedIds(submission.getSelectedResourceIds()); if (selected.isEmpty() || !allowed.containsAll(selected)) throw new IllegalArgumentException("select at least one assigned map resource"); } if (task.getDueAt() != null && task.getDueAt().isBefore(LocalDateTime.now()) && !Boolean.TRUE.equals(task.getAllowLateSubmission())) throw new IllegalArgumentException("late submission is not allowed"); }
    private StudentTaskDetailVO taskDetail(ClassLearningTask task, StudentTaskSubmission submission) { StudentTaskDetailVO vo = new StudentTaskDetailVO(); fillTask(vo, task); vo.setTaskType(task.getTaskType()); vo.setSubmissionRule(task.getSubmissionRule()); vo.setAllowLateSubmission(Boolean.TRUE.equals(task.getAllowLateSubmission())); List<Long> resourceIds = taskResourceMapper.selectList(new LambdaQueryWrapper<TaskResourceRel>().eq(TaskResourceRel::getTaskId, task.getTaskId()).orderByAsc(TaskResourceRel::getSortOrder)).stream().map(TaskResourceRel::getResourceId).toList(); if (!resourceIds.isEmpty()) vo.setResources(resourceMapper.selectBatchIds(resourceIds).stream().map(this::resourceVO).toList()); if (submission != null) vo.setCurrentSubmission(submissionVO(submission)); return vo; }
    private void fillTask(ClassTaskVO vo, ClassLearningTask task) { vo.setTaskId(task.getTaskId()); vo.setClassId(task.getClassId()); vo.setTitle(task.getTitle()); vo.setDescription(task.getDescription()); vo.setPublishedAt(task.getPublishedAt()); vo.setDueAt(task.getDueAt()); vo.setStatus(task.getStatus()); }
    private TaskResourceVO resourceVO(LocalEduResource resource) { TaskResourceVO vo = new TaskResourceVO(); vo.setResourceId(resource.getResourceId()); vo.setResourceName(resource.getResourceName()); vo.setAddress(resource.getAddress()); vo.setLongitude(resource.getLongitude()); vo.setLatitude(resource.getLatitude()); vo.setIntro(resource.getIntro()); vo.setEducationValue(resource.getEducationValue()); vo.setSafetyNote(resource.getSafetyNote()); return vo; }
    private StudentTaskSubmissionVO submissionVO(StudentTaskSubmission entity) { StudentTaskSubmissionVO vo = new StudentTaskSubmissionVO(); vo.setSubmissionId(entity.getSubmissionId()); vo.setTaskId(entity.getTaskId()); vo.setStudentId(entity.getStudentId()); StudentProfile student = studentMapper.selectById(entity.getStudentId()); vo.setStudentName(student == null ? null : student.getStudentName()); vo.setVersionNo(entity.getVersionNo()); vo.setContent(entity.getContent()); vo.setSelectedResourceIds(new ArrayList<>(selectedIds(entity.getSelectedResourceIds()))); vo.setSubmittedAt(entity.getSubmittedAt()); vo.setLate(Boolean.TRUE.equals(entity.getLate())); vo.setStatus(entity.getStatus()); vo.setCurrent(Boolean.TRUE.equals(entity.getCurrent())); vo.setAttachments(attachmentMapper.selectList(new LambdaQueryWrapper<StudentTaskAttachment>().eq(StudentTaskAttachment::getSubmissionId, entity.getSubmissionId())).stream().map(this::attachmentVO).toList()); vo.setReviews(reviewMapper.selectList(new LambdaQueryWrapper<StudentTaskReview>().eq(StudentTaskReview::getSubmissionId, entity.getSubmissionId()).orderByAsc(StudentTaskReview::getReviewedAt)).stream().map(this::reviewVO).toList()); return vo; }
    private StudentTaskAttachmentVO attachmentVO(StudentTaskAttachment entity) { StudentTaskAttachmentVO vo = new StudentTaskAttachmentVO(); vo.setAttachmentId(entity.getAttachmentId()); vo.setOriginalFilename(entity.getOriginalFilename()); vo.setContentType(entity.getContentType()); vo.setFileSize(entity.getFileSize()); return vo; }
    private StudentTaskReviewVO reviewVO(StudentTaskReview entity) { StudentTaskReviewVO vo = new StudentTaskReviewVO(); vo.setReviewId(entity.getReviewId()); TeacherProfile teacher = teacherMapper.selectById(entity.getTeacherId()); vo.setTeacherName(teacher == null ? null : teacher.getTeacherName()); vo.setReviewAction(entity.getReviewAction()); vo.setComment(entity.getComment()); vo.setGrade(entity.getGrade()); vo.setReviewedAt(entity.getReviewedAt()); return vo; }
    private ClassLearningTask requireTask(Long taskId) { ClassLearningTask task = taskMapper.selectById(taskId); if (task == null) throw new IllegalArgumentException("task not found"); return task; }
    private ClassLearningTask requirePublishedTask(Long taskId) { ClassLearningTask task = requireTask(taskId); if (!"published".equals(task.getStatus())) throw new IllegalArgumentException("task is not available for submission"); return task; }
    private StudentTaskSubmission requireSubmission(Long id) { StudentTaskSubmission submission = submissionMapper.selectById(id); if (submission == null) throw new IllegalArgumentException("submission not found"); return submission; }
    private StudentTaskSubmission currentSubmission(Long taskId, Long studentId) { return submissionMapper.selectOne(new LambdaQueryWrapper<StudentTaskSubmission>().eq(StudentTaskSubmission::getTaskId, taskId).eq(StudentTaskSubmission::getStudentId, studentId).eq(StudentTaskSubmission::getCurrent, true).last("LIMIT 1")); }
    private StudentTaskSubmission requireOwnedDraft(Long id, StudentProfile student) { StudentTaskSubmission submission = requireSubmission(id); if (!student.getStudentId().equals(submission.getStudentId()) || !submission.getCurrent() || !"draft".equals(submission.getStatus())) throw new IllegalArgumentException("submission is not editable"); return submission; }
    private StudentTaskProgress requireProgress(Long taskId, Long studentId) { StudentTaskProgress progress = progressMapper.selectOne(new LambdaQueryWrapper<StudentTaskProgress>().eq(StudentTaskProgress::getTaskId, taskId).eq(StudentTaskProgress::getStudentId, studentId).last("LIMIT 1")); if (progress == null) throw new IllegalArgumentException("task is not assigned to this student"); return progress; }
    private StudentProfile requireStudent(AuthCurrentUserVO user) { if (user == null || !"student".equals(user.getRoleCode())) throw new IllegalArgumentException("student access required"); StudentProfile student = studentMapper.selectOne(new LambdaQueryWrapper<StudentProfile>().eq(StudentProfile::getAccountId, user.getAccountId()).eq(StudentProfile::getStatus, "active").last("LIMIT 1")); if (student == null) throw new IllegalArgumentException("active student profile is required"); return student; }
    private TeacherProfile requirePublisher(Long taskId, AuthCurrentUserVO user) { if (user == null || !"teacher".equals(user.getRoleCode())) throw new IllegalArgumentException("teacher access required"); TeacherProfile teacher = teacherMapper.selectOne(new LambdaQueryWrapper<TeacherProfile>().eq(TeacherProfile::getAccountId, user.getAccountId()).eq(TeacherProfile::getStatus, "active").last("LIMIT 1")); ClassLearningTask task = requireTask(taskId); if (teacher == null || !teacher.getTeacherId().equals(task.getPublisherTeacherId())) throw new IllegalArgumentException("only the task publisher can review submissions"); return teacher; }
    private void requireActiveMember(ClassLearningTask task, Long studentId) { if (memberMapper.selectCount(new LambdaQueryWrapper<ClassMember>().eq(ClassMember::getClassId, task.getClassId()).eq(ClassMember::getStudentId, studentId).eq(ClassMember::getStatus, "active")) == 0) throw new IllegalArgumentException("student is not an active class member"); }
    private boolean canReadSubmission(StudentTaskSubmission submission, AuthCurrentUserVO user) { if (user == null) return false; if ("student".equals(user.getRoleCode())) { StudentProfile student = studentMapper.selectOne(new LambdaQueryWrapper<StudentProfile>().eq(StudentProfile::getAccountId, user.getAccountId()).last("LIMIT 1")); return student != null && student.getStudentId().equals(submission.getStudentId()); } if ("teacher".equals(user.getRoleCode())) { try { requirePublisher(submission.getTaskId(), user); return true; } catch (IllegalArgumentException ignored) { return false; } } return "school_admin".equals(user.getRoleCode()) || "platform_admin".equals(user.getRoleCode()); }
    private Set<Long> selectedIds(String csv) { if (!StringUtils.hasText(csv)) return Collections.emptySet(); return Arrays.stream(csv.split(",")).map(String::trim).filter(StringUtils::hasText).map(Long::valueOf).collect(Collectors.toCollection(LinkedHashSet::new)); }
}
