package com.redculture.platform.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.redculture.platform.entity.*;
import com.redculture.platform.enums.ReviewStatus;
import com.redculture.platform.mapper.*;
import com.redculture.platform.service.TeacherResourceService;
import com.redculture.platform.vo.AuthCurrentUserVO;
import com.redculture.platform.vo.TeacherResourceVO;
import com.redculture.platform.vo.request.TeacherResourceQueryRequest;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
@Service public class TeacherResourceServiceImpl implements TeacherResourceService {
 private final TeacherProfileMapper teacherMapper; private final SchoolResourceRelMapper relationMapper; private final LocalEduResourceMapper resourceMapper; private final TeacherResourceFavoriteMapper favoriteMapper;
 public TeacherResourceServiceImpl(TeacherProfileMapper teacherMapper, SchoolResourceRelMapper relationMapper, LocalEduResourceMapper resourceMapper, TeacherResourceFavoriteMapper favoriteMapper) { this.teacherMapper=teacherMapper;this.relationMapper=relationMapper;this.resourceMapper=resourceMapper;this.favoriteMapper=favoriteMapper; }
 @Override public List<TeacherResourceVO> nearby(TeacherResourceQueryRequest query, AuthCurrentUserVO user) { TeacherProfile teacher=teacher(user); List<TeacherResourceVO> items=available(teacher); return filter(items,query); }
 @Override public List<TeacherResourceVO> favorites(AuthCurrentUserVO user) { TeacherProfile teacher=teacher(user); Set<Long> ids=favoriteIds(teacher.getTeacherId()); Map<Long,TeacherResourceVO> available=available(teacher).stream().collect(Collectors.toMap(TeacherResourceVO::getResourceId, Function.identity())); return ids.stream().map(id -> { TeacherResourceVO item=available.get(id); if(item!=null)return item; LocalEduResource resource=resourceMapper.selectById(id); if(resource==null)return null; TeacherResourceVO stale=resourceVo(resource,null,true);stale.setAvailable(false);return stale; }).filter(Objects::nonNull).sorted(Comparator.comparing(TeacherResourceVO::isAvailable).reversed().thenComparing(TeacherResourceVO::getResourceName,Comparator.nullsLast(String::compareTo))).toList(); }
 @Override public List<TeacherResourceVO> selection(AuthCurrentUserVO user) { TeacherProfile teacher=teacher(user); Set<Long> favorite=favoriteIds(teacher.getTeacherId()); return available(teacher).stream().sorted(Comparator.comparing((TeacherResourceVO item)->!favorite.contains(item.getResourceId())).thenComparing(TeacherResourceVO::getPriorityLevel,Comparator.nullsLast(Integer::compareTo)).thenComparing(TeacherResourceVO::getDistanceMeters,Comparator.nullsLast(Integer::compareTo))).toList(); }
 @Override public TeacherResourceVO detail(Long resourceId, AuthCurrentUserVO user) { TeacherProfile teacher=teacher(user); TeacherResourceVO result=available(teacher).stream().filter(item->item.getResourceId().equals(resourceId)).findFirst().orElse(null); if(result!=null)return result; if(favoriteIds(teacher.getTeacherId()).contains(resourceId)){LocalEduResource resource=resourceMapper.selectById(resourceId);if(resource!=null){TeacherResourceVO stale=resourceVo(resource,null,true);stale.setAvailable(false);return stale;}} throw new IllegalArgumentException("resource not found"); }
 @Override public void favorite(Long resourceId, AuthCurrentUserVO user) { TeacherProfile teacher=teacher(user); boolean present=available(teacher).stream().anyMatch(item->item.getResourceId().equals(resourceId)); if(!present)throw new IllegalArgumentException("resource is not available to this school"); if(favoriteMapper.selectCount(new LambdaQueryWrapper<TeacherResourceFavorite>().eq(TeacherResourceFavorite::getTeacherId,teacher.getTeacherId()).eq(TeacherResourceFavorite::getResourceId,resourceId))==0){TeacherResourceFavorite item=new TeacherResourceFavorite();item.setTeacherId(teacher.getTeacherId());item.setResourceId(resourceId);favoriteMapper.insert(item);} }
 @Override public void unfavorite(Long resourceId, AuthCurrentUserVO user) { TeacherProfile teacher=teacher(user); favoriteMapper.delete(new LambdaQueryWrapper<TeacherResourceFavorite>().eq(TeacherResourceFavorite::getTeacherId,teacher.getTeacherId()).eq(TeacherResourceFavorite::getResourceId,resourceId)); }
 private List<TeacherResourceVO> available(TeacherProfile teacher){ Set<Long> favorites=favoriteIds(teacher.getTeacherId()); Map<Long,SchoolResourceRel> best=new HashMap<>(); for(SchoolResourceRel rel:relationMapper.selectList(new LambdaQueryWrapper<SchoolResourceRel>().eq(SchoolResourceRel::getSchoolId,teacher.getSchoolId()).eq(SchoolResourceRel::getReviewStatus,ReviewStatus.APPROVED))){best.merge(rel.getResourceId(),rel,(a,b)->compare(a,b)<=0?a:b);} if(best.isEmpty())return List.of(); Map<Long,LocalEduResource> resources=resourceMapper.selectBatchIds(best.keySet()).stream().filter(item->Boolean.TRUE.equals(item.getActive())&&item.getReviewStatus()==ReviewStatus.APPROVED).collect(Collectors.toMap(LocalEduResource::getResourceId,Function.identity())); return best.entrySet().stream().filter(item->resources.containsKey(item.getKey())).map(item->resourceVo(resources.get(item.getKey()),item.getValue(),favorites.contains(item.getKey()))).sorted(Comparator.comparing(TeacherResourceVO::getPriorityLevel,Comparator.nullsLast(Integer::compareTo)).thenComparing(TeacherResourceVO::getDistanceMeters,Comparator.nullsLast(Integer::compareTo)).thenComparing(TeacherResourceVO::getResourceName,Comparator.nullsLast(String::compareTo))).toList(); }
 private List<TeacherResourceVO> filter(List<TeacherResourceVO> items,TeacherResourceQueryRequest q){if(q==null)return items;return items.stream().filter(i->!Boolean.TRUE.equals(q.getFavoritesOnly())||i.isFavorited()).filter(i->!StringUtils.hasText(q.getKeyword())||contains(i.getResourceName(),q.getKeyword())||contains(i.getEducationThemeSummary(),q.getKeyword())).filter(i->!StringUtils.hasText(q.getCategory())||q.getCategory().equals(i.getResourceCategory())).filter(i->!StringUtils.hasText(q.getGradeName())||contains(i.getTargetGrade(),q.getGradeName())).filter(i->!StringUtils.hasText(q.getTravelMode())||q.getTravelMode().equals(i.getTravelMode())).filter(i->!StringUtils.hasText(q.getReachabilityLevel())||q.getReachabilityLevel().equals(i.getReachabilityLevel())).filter(i->q.getMaxDistanceMeters()==null||i.getDistanceMeters()==null||i.getDistanceMeters()<=q.getMaxDistanceMeters()).toList();}
 private boolean contains(String value,String query){return value!=null&&value.toLowerCase(Locale.ROOT).contains(query.trim().toLowerCase(Locale.ROOT));} private int compare(SchoolResourceRel a,SchoolResourceRel b){int p=Comparator.nullsLast(Integer::compareTo).compare(a.getPriorityLevel(),b.getPriorityLevel());return p!=0?p:Comparator.nullsLast(Integer::compareTo).compare(a.getDistanceMeters(),b.getDistanceMeters());} private Set<Long> favoriteIds(Long id){return favoriteMapper.selectList(new LambdaQueryWrapper<TeacherResourceFavorite>().eq(TeacherResourceFavorite::getTeacherId,id)).stream().map(TeacherResourceFavorite::getResourceId).collect(Collectors.toSet());} private TeacherProfile teacher(AuthCurrentUserVO u){if(u==null||!"teacher".equals(u.getRoleCode()))throw new IllegalArgumentException("teacher access required");TeacherProfile t=teacherMapper.selectOne(new LambdaQueryWrapper<TeacherProfile>().eq(TeacherProfile::getAccountId,u.getAccountId()).eq(TeacherProfile::getStatus,"active").last("LIMIT 1"));if(t==null)throw new IllegalArgumentException("active teacher profile is required");return t;} private TeacherResourceVO resourceVo(LocalEduResource r,SchoolResourceRel rel,boolean f){TeacherResourceVO v=new TeacherResourceVO();v.setResourceId(r.getResourceId());v.setResourceName(r.getResourceName());v.setResourceCategory(r.getResourceCategory()==null?null:r.getResourceCategory().getValue());v.setTargetGrade(r.getTargetGrade());v.setAddress(r.getAddress());v.setLongitude(r.getLongitude());v.setLatitude(r.getLatitude());v.setIntro(r.getIntro());v.setEducationValue(r.getEducationValue());v.setSafetyNote(r.getSafetyNote());v.setFavorited(f);v.setAvailable(true);if(rel!=null){v.setDistanceMeters(rel.getDistanceMeters());v.setPriorityLevel(rel.getPriorityLevel());v.setTravelMode(rel.getRecommendedTravelMode()==null?null:rel.getRecommendedTravelMode().getValue());v.setDurationMinutes(rel.getEstimatedDurationMinutes());v.setReachabilityLevel(rel.getReachabilityLevel()==null?null:rel.getReachabilityLevel().getValue());v.setEducationThemeSummary(rel.getEducationThemeSummary());}return v;}
}
